{
 "title": "Magpie",
 "time": { "from": "2021-01-13T16:33:59.169Z", "to": "2021-01-13T18:39:45.694Z" },
 "panels": [
  {
   "title": "iperf client bandwidth (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(magpie_iperf_bandwidth[30s]))",
     "legendFormat": "bandwidth"
    }
   ]
  },
  {
   "title": "iperf bandwidth (unit)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(magpie_iperf_bandwidth[600s])",
     "legendFormat": "{{src}}"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "sum(irate(net_bytes_recv[5m]))", "legendFormat": "received" },
    { "expr": "sum(irate(net_bytes_sent[5m]))", "legendFormat": "sent" }
   ]
  }
 ]
}