{
 "title": "Storage Benchmarks",
 "time": {
  "from": "2020-11-26T12:30:00.000Z",
  "raw": { "from": "2020-11-26T12:30:00.000Z", "to": "2020-11-26T13:47:00.000Z" },
  "to": "2020-11-26T13:47:00.000Z"
 },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval" },
   { "name": "cluster", "label": "cluster" },
   { "name": "model", "label": "model" }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "avg"
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg"
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Bcache Dirty Data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ]
  },
  {
   "title": "Bcache Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ]
  },
  { "title": "Ceph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ]
  },
  {
   "title": "Client FIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIO Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(fio_read_bandwidth{model=\"$model\"}[30s]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(avg_over_time(fio_write_bandwidth{model=\"$model\"}[30s]))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "FIO IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(fio_read_iops{model=\"$model\"}[30s]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(avg_over_time(fio_write_iops{model=\"$model\"}[30s]))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "FIO latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(fio_read_latency{model=\"$model\"}[30s]))",
       "legendFormat": "read"
      },
      {
       "expr": "avg(avg_over_time(fio_write_latency{model=\"$model\"}[30s]))",
       "legendFormat": "write"
      }
     ]
    }
   ]
  }
 ]
}