{
 "title": "Woodpecker",
 "time": { "from": "2021-02-17T13:16:36.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" },
   { "name": "model", "label": "model", "query": "label_values(model)" }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(system_n_cpus)" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(mem_total)" }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(disk_total)" }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(disk_total)" }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(cpu_usage_user{cpu=\"cpu-total\"})",
     "legendFormat": "user"
    },
    {
     "expr": "sum(cpu_usage_iowait{cpu=\"cpu-total\"})",
     "legendFormat": "iowait "
    },
    {
     "expr": "sum(cpu_usage_nice{cpu=\"cpu-total\"})",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(cpu_usage_softirq{cpu=\"cpu-total\"})",
     "legendFormat": "softirq "
    },
    {
     "expr": "sum(cpu_usage_irq{cpu=\"cpu-total\"})",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(cpu_usage_system{cpu=\"cpu-total\"})",
     "legendFormat": "system "
    },
    {
     "expr": "sum(cpu_usage_idle{cpu=\"cpu-total\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(diskio_reads{name!~\".*(bcache|loop|crypt|n1p|ceph).*\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(diskio_writes{name!~\".*(bcache|loop|crypt|n1p|ceph).*\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(diskio_reads{name=~\".*bcache.*\"}[5m]))",
     "legendFormat": "read - bcache"
    },
    {
     "expr": "sum(irate(diskio_writes{name=~\".*bcache.*\"}[5m]))",
     "legendFormat": "write - bcache"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "sum(irate(net_bytes_recv[5m]))", "legendFormat": "received" },
    { "expr": "sum(irate(net_bytes_sent[5m]))", "legendFormat": "sent" }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(system_load1[5m]))  ",
     "legendFormat": "1 min"
    },
    {
     "expr": "sum(avg_over_time(system_load5[5m]))",
     "legendFormat": "5 min"
    },
    {
     "expr": "sum(avg_over_time(system_load15[5m]))  ",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(diskio_read_bytes{name!~\".*(bcache|loop|crypt|n1p).*\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(diskio_write_bytes{name!~\".*(bcache|loop|crypt|n1p).*\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(diskio_read_bytes{name=~\".*bcache.*\"}[5m]))",
     "legendFormat": "read - bcache"
    },
    {
     "expr": "sum(irate(diskio_write_bytes{name=~\".*bcache.*\"}[5m]))",
     "legendFormat": "write - bcache"
    }
   ]
  },
  {
   "title": "Bcache Dirty Data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(bcache_dirty_data)", "legendFormat": "Dirty Data" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(mem_used)", "legendFormat": "Used" },
    { "expr": "sum(mem_free)  ", "legendFormat": "Free" },
    { "expr": "sum(mem_buffered + mem_cached)", "legendFormat": "Buffers/Cache" }
   ]
  },
  {
   "title": "Bcache Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "avg(bcache_cache_hit_ratio)", "legendFormat": "Hit ratio (avg)" }
   ]
  },
  { "title": "Ceph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes[$interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes[$interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w[$interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r[$interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "apply (average)" },
    {
     "expr": "quantile(0.95, ceph_osd_apply_latency_ms)",
     "legendFormat": "apply (95 percentile)"
    }
   ]
  },
  { "title": "Client FIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "FIO Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fio_read_bandwidth{model=\"$model\"}[30s]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(avg_over_time(fio_write_bandwidth{model=\"$model\"}[30s]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "FIO IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fio_read_iops{model=\"$model\"}[30s]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(avg_over_time(fio_write_iops{model=\"$model\"}[30s]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "FIO latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(fio_read_latency{model=\"$model\"}[30s]))",
     "legendFormat": "read"
    },
    {
     "expr": "avg(avg_over_time(fio_write_latency{model=\"$model\"}[30s]))",
     "legendFormat": "write"
    },
    {
     "expr": "quantile(0.95, fio_read_latency{model=\"$model\"})",
     "legendFormat": "read - 95%tile"
    },
    {
     "expr": "quantile(0.95, fio_write_latency{model=\"$model\"})",
     "legendFormat": "write - 95%tile"
    }
   ]
  },
  {
   "title": "FIO Bandwidth (per client)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(fio_read_bandwidth{model=\"$model\"}[5m])",
     "legendFormat": "{{unit}} - read"
    },
    {
     "expr": "avg_over_time(fio_write_bandwidth{model=\"$model\"}[5m])",
     "legendFormat": "{{unit}} - write"
    }
   ]
  },
  {
   "title": "FIO IOPS (per client)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(fio_read_iops{model=\"$model\"}[5m])",
     "legendFormat": "{{unit}} - read"
    },
    {
     "expr": "avg_over_time(fio_write_iops{model=\"$model\"}[5m])",
     "legendFormat": "{{unit}} - write"
    }
   ]
  },
  {
   "title": "FIO clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(fio_read_bandwidth{unit=~\".*\",model=\"$model\"}) by (unit))\n",
     "legendFormat": "readers"
    },
    {
     "expr": "count(count(fio_write_bandwidth{unit=~\".*\",model=\"$model\"}) by (unit))\n",
     "legendFormat": "writers"
    }
   ]
  }
 ]
}